name: riscv-dbg compilation
on: 
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-19.04
    env:
      RISCV: "/home/travis/riscv_install"
      VERILATOR_ROOT: "/home/travis/verilator-4.018"
    steps:
     - name: Install dependencies
     - run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test && sudo apt-get install -y gcc-7 g++-7 gperf autoconf automake autotools-dev libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo python pexpect libusb-1.0-1-dev default-jdk zlib1g-dev valgrind
     - name: Cache multiple paths
     - uses: actions/cache@v2
       with:
        path: $RISCV $VERILATOR_ROOT
     - uses: actions/checkout@v2
#      set environment variables for the shell
     - run: export CXX=g++-7 CC=gcc-7
     - run: export PATH=$RISCV/bin:$VERILATOR_ROOT/bin:$PATH
     - run: export LIBRARY_PATH=$RISCV/lib
     - run: export LD_LIBRARY_PATH=$RISCV/lib
     - run: export C_INCLUDE_PATH=$RISCV/include:$VERILATOR_ROOT/share/verilator/include
     - run: export CPLUS_INCLUDE_PATH=$RISCV/include:$VERILATOR_ROOT/share/verilator/include
     - run: export PKG_CONFIG_PATH=$VERILATOR_ROOT/share/pkgconfig
     - run: export NUM_JOBS=4
     - run: ci/make-tmp.sh
     - run: git submodule update --init --recursive
#      Download Pulp GCC
     - run: ci/downoad-pulp-gcc.sh
#      Build Verilator
     - run: ci/install-verilator.sh
#      Build OpenOCD
     - run: ci/get-openocd.sh
#      Run OpenOCD debug module tests
     - run: ci/veri-run-openocd-compliance.sh
